"""add_avatar_url_to_users

Revision ID: 32c3d4fc9073
Revises: 3bd46a88d0cf
Create Date: 2026-09-10 16:37:38.686442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c3d4fc9073'
down_revision: Union[str, Sequence[str], None] = '3bd46a88d0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freelancer_profiles', 'avatar_url')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.add_column('freelancer_profiles', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
