"""add_file_storage_and_attachments

Revision ID: 3bd46a88d0cf
Revises: 6e651c09a764
Create Date: 2026-09-09 17:27:26.365212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd46a88d0cf'
down_revision: Union[str, Sequence[str], None] = '6e651c09a764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestone_attachments_milestone_id'), 'milestone_attachments', ['milestone_id'], unique=False)
    op.add_column('freelancer_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freelancer_profiles', 'avatar_url')
    op.drop_index(op.f('ix_milestone_attachments_milestone_id'), table_name='milestone_attachments')
    op.drop_table('milestone_attachments')
    # ### end Alembic commands ###
